import axios from "axios";
import { OpenAI } from "langchain/llms/openai";
import { LLMChain } from "langchain/chains";
import { PromptTemplate } from "langchain/prompts";

const GRAPH_API_BASE = "https://graph.microsoft.com/v1.0";

async function getAccessToken(): Promise<string> {
  const tenantId = process.env.MS_GRAPH_TENANT_ID!;
  const clientId = process.env.MS_GRAPH_CLIENT_ID!;
  const clientSecret = process.env.MS_GRAPH_CLIENT_SECRET!;

  const response = await axios.post(
    `https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/token`,
    new URLSearchParams({
      grant_type: "client_credentials",
      client_id: clientId,
      client_secret: clientSecret,
      scope: "https://graph.microsoft.com/.default",
    }),
    { headers: { "Content-Type": "application/x-www-form-urlencoded" } }
  );

  return response.data.access_token as string;
}

export interface EmailItem {
  subject: string;
  from: string;
  receivedDateTime: string;
  bodyPreview: string;
}

export async function fetchUnreadEmails(userEmail: string): Promise<EmailItem[]> {
  const token = await getAccessToken();

  const since = new Date();
  since.setHours(since.getHours() - 24);
  const sinceISO = since.toISOString();

  const response = await axios.get(
    `${GRAPH_API_BASE}/users/${userEmail}/mailFolders/inbox/messages`,
    {
      headers: { Authorization: `Bearer ${token}` },
      params: {
        $filter: `isRead eq false and receivedDateTime ge ${sinceISO}`,
        $select: "subject,from,receivedDateTime,bodyPreview",
        $orderby: "receivedDateTime desc",
        $top: 50,
      },
    }
  );

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (response.data.value as any[]).map((msg) => ({
    subject: msg.subject as string,
    from: (msg.from?.emailAddress?.address ?? "Unknown") as string,
    receivedDateTime: msg.receivedDateTime as string,
    bodyPreview: msg.bodyPreview as string,
  }));
}

export async function summarizeEmails(emails: EmailItem[]): Promise<string> {
  if (emails.length === 0) {
    return "No new unread emails in the last 24 hours.";
  }

  const emailList = emails
    .map(
      (e, i) =>
        `${i + 1}. From: ${e.from}\n   Subject: ${e.subject}\n   Preview: ${e.bodyPreview}`
    )
    .join("\n\n");

  const prompt = new PromptTemplate({
    template: `You are an AI assistant. Summarize the following unread emails into a concise daily digest.
Group related topics together and clearly flag any items that require action or are urgent.

Emails:
{emails}

Provide a structured summary with sections: Key Actions Required, Important Updates, and FYI / Low Priority.`,
    inputVariables: ["emails"],
  });

  const llm = new OpenAI({
    openAIApiKey: process.env.OPENAI_API_KEY,
    modelName: "gpt-3.5-turbo-instruct",
    temperature: 0.3,
    maxTokens: 1000,
  });

  const chain = new LLMChain({ llm, prompt });
  const result = await chain.call({ emails: emailList });
  return result.text as string;
}

export async function sendSummaryEmail(
  userEmail: string,
  summary: string,
  emailCount: number
): Promise<void> {
  const token = await getAccessToken();

  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const htmlBody = `
    <div style="font-family: Arial, sans-serif; max-width: 640px; margin: 0 auto;">
      <h2 style="color: #1a1a2e;">Daily Email Summary &mdash; ${today}</h2>
      <p><strong>${emailCount} unread email(s)</strong> received in the last 24 hours</p>
      <hr style="border: none; border-top: 1px solid #eee;" />
      <div style="white-space: pre-wrap; line-height: 1.6;">${summary}</div>
      <hr style="border: none; border-top: 1px solid #eee;" />
      <p style="color: #999; font-size: 12px;">Generated by AgentGPT Daily Email Summary</p>
    </div>
  `;

  await axios.post(
    `${GRAPH_API_BASE}/users/${userEmail}/sendMail`,
    {
      message: {
        subject: `Daily Email Summary — ${today}`,
        body: { contentType: "HTML", content: htmlBody },
        toRecipients: [{ emailAddress: { address: userEmail } }],
      },
      saveToSentItems: false,
    },
    {
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
    }
  );
}
